routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// admin login and register
Route::namespace('Auth\Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    
    Route::post('admin/login', 'LoginController@login')->name('admin.login.submit');
    
    Route::post('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::get('/admin/register', 'AregisterController@create')->name('admin.register');
Route::post('/save', 'AregisterController@store');
Route::get('/admin', 'ALoginController@index')->name('admin');
Route::get('/view', 'ALoginController@create')->name('view');
Route::resource('job','AJobController');
Route::resource('company','CompanyController');
Route::get('/detail/{id}','JobcvController@show')->name('detail');



// user login and signup
Route::namespace('Auth\User')->group(function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('auth.login');  
    Route::post('/login', 'LoginController@login')->name('login.submit');
    Route::post('/logout', 'LoginController@logout')->name('auth.logout');
});

Route::get('/register', 'RegisterController@create')->name('register');
Route::post('/post', 'RegisterController@store');


Route::resource('/', 'UserController');
Route::get('/save/{filename}', 'DownloadController@download')->name('save.cv');




// User update
Route::get('user','UpdateController@index')->name('user');
Route::get('user/profile','UserController@index')->name('profile');
Route::patch('user/profile/{id}','UserController@update');

Route::get('user/update','UpdateController@create')->name('edit');
Route::patch('/user/update/{id}','UpdateController@update')->name('update');

//Job
Route::resource('search','JobController');
Route::get('jobcv/{id}','JobcvController@store')->name('jobcv.store');
Route::get('/jobapply','JobcvController@index')->name('jobcv.index');
//Home

Route::resource('home','HomeController');

// SearchBox
Route::post('/searchjob','SearchController@Searchbox');

Route::get('/searchbycate','SearchController@searchbycate');

resources/views/a.blade.php
<!DOCTYPE HTML>
<!--
    Synchronous by TEMPLATED
    templated.co @templatedco
    Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
    <head>
        <title>FindOne</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
        {{-- <script src="/template/js/html5shiv.js"></script> --}}
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="/template/js/skel.min.js"></script>
        <script src="/template/js/skel-panels.min.js"></script>
        <script src="/template/js/init.js"></script>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
        
     {{-- <noscript> --}}
         <link rel="stylesheet" href="/template/css/skel-noscript.css" />
     {{-- </noscript> --}}
        
        <link rel="stylesheet" type="text/css" href="/template/css/style-desktop.css">
        <link rel="stylesheet" href="/template/css/style.css" />
        
        {{-- <link rel="stylesheet" href="/template/css/ie/v8.css" /> --}}
      
      {{-- <link rel="stylesheet" href="/template/css/ie/v9.css" /> --}}
    </head>
    <body class="homepage">
        <div id="wrapper">
            
            <!-- Header -->
            <div id="header">
                <div class="container"> 
                    
                    <!-- Logo -->
                    <div id="logo">
                        <img src="/images/za.png" width="150px" height="150px">
                        
                    </div>
                    
                    <!-- Nav -->
                    <nav id="nav">
                        <ul>
                            <li class="active"><a href="index.html">Homepage</a></li>
                            <li><a href="{{ route('auth.login') }}">User Login</a></li>
                            <li><a href="{{ route('register') }}"">Registration</a></li>
                            <li><a href="{{ route('search.index') }}">Search Job</a></li>
                            <li><a href="onecolumn.html">Employer</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /Header -->
            
            <div id="page">
                <div class="container">
                    <div class="row">
                        <div class="3u">
                            
                            <section id="sidebar1">
                                <header>
                                    <h2>Companies</h2>
                                </header>

                                
                                @foreach( $jobs as $job )
                                <div style="text-align: center" class="form-control">
                                    <a href=""><img src="/logo/{{ $job->company['logo'] }}"  height="90px"></a>
                                </div>
                                    
                                
                                @endforeach;
                                
                            
                            </section>
                        </div>
                        <div class="6u skel-cell-important">
                            <section id="content" >
                                <header style="text-align: center">
                                    <h2>Jobs</h2>
                                </header>
                                

                                
                               
                                <div class="row">
                                @foreach( $jobs as $job )
                                 
                                 
                                
                                <div style="width: 300px;">  
                                
                                    
                                
                                <h3><a  href="{{ route('search.show', $job->id) }}"><strong style="color: green; font-size: 22px;">{{ $job->jobtitle }}</strong></a></h3>
                               
                                <h4 style="color: black"> {{ $job->company['companyname'] }} </h4>
                                
                                <hr style=" border-bottom: 3px dashed #ccc;">
                                </div>
                                
                                


                                
                                
                                
                                
                                @endforeach
                                
                                </div>
                                
                                
                            </section>
                        </div>
                        <div class="3u">
                            <section id="sidebard2">
                                <header>
                                    <h2>Sidebar 2</h2>
                                </header>
                                <ul class="style1">
                                    <li class="first"><span class="fa fa-check"></span><a href="#">Maecenas luctus lectus at sapien</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Etiam rhoncus volutpat erat</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Donec dictum metus in sapien</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Integer gravida nibh quis urna</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Etiam posuere augue sit amet nisl</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Mauris vulputate dolor nibh</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Nulla luctus eleifend purus</a></li>
                                </ul>
                                <a href="#" class="button">Full Article</a>
                            </section>
                        </div>
                    </div>

                </div>  
            </div>

            <!-- Footer -->
            <div id="footer">
                <div class="container">
                    <div class="row">
                        <div class="3u">
                            <section id="box1">
                                <header>
                                    <h2>Nulla facilisi</h2>
                                </header>
                                <ul class="style3">
                                    <li class="first">
                                        <p class="date"><a href="#">10.03.2012</a></p>
                                        <p><a href="#">Vestibulum sem magna, elementum ut, vestibulum facilisis. Nulla facilisi. Cum sociis natoque penatibus.</a></p>
                                    </li>
                                    <li>
                                        <p class="date"><a href="#">10.03.2012</a></p>
                                        <p><a href="#">Pellentesque erat erat, tincidunt in, eleifend, malesuada bibendum. Suspendisse sit amet  in eros bibendum condimentum. </a> </p>
                                    </li>
                                </ul>
                            </section>
                        </div>
                        <div class="6u">
                            <section id="box2">
                                <header>
                                    <h2>Donec dictum metus</h2>
                                </header>
                                <div> <a href="#" class="image full"><img src="images/pics02.jpg" alt=""></a> </div>
                                <p>Nulla enim eros, porttitor eu, tempus id, varius non, nibh. Duis enim nulla, luctus eu, dapibus lacinia, venenatis id, quam. Vestibulum imperdiet, magna nec eleifend rutrum, nunc lectus vestibulum velit, euismod lacinia quam nisl id lorem. Quisque erat. Vestibulum pellentesque, justo mollis pretium suscipit, justo nulla blandit libero, in blandit augue justo quis nisl.</p>
                            </section>
                        </div>
                        <div class="3u">
                            <section id="box3">
                                <header>
                                    <h2>Gravida ipsum</h2>
                                </header>
                                <ul class="style1">
                                    <li class="first"><a href="#">Pellentesque quis elit non lectus eleifend purus condimentum.</a></li>
                                    <li><a href="#">Lorem ipsum dolort, consectetuer adipiscing dictum metus sapien.</a></li>
                                    <li><a href="#">Phasellus nec dictum metus in sapien pellentesque congue.</a></li>
                                    <li><a href="#">Cras vitae metus aliquam risus dictum metus in sapien pharetra.</a></li>
                                    <li><a href="#">Duis non dictum metus in sapien ante in metus commodo euismod lobortis.</a></li>
                                </ul>
                            </section>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Copyright -->
            <div id="copyright">
                <div class="container">
                    Design: <a href="http://templated.co">TEMPLATED</a> Images: <a href="http://unsplash.com">Unsplash</a> (<a href="http://unsplash.com/cc0">CC0</a>)
                </div>
            </div>
            
        </div>
    </body>
</html>

resources/views/e.blade.php
<!DOCTYPE HTML>
<!--
    Synchronous by TEMPLATED
    templated.co @templatedco
    Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
    <head>
        <title>ZA</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="keywords" content="footer, contact, form, icons" />
        <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
        {{-- <script src="/template/js/html5shiv.js"></script> --}}
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="/template/js/skel.min.js"></script>
        <script src="/template/js/skel-panels.min.js"></script>
        <script src="/template/js/init.js"></script>

        
        <link rel="stylesheet" href="footer/footer.css">

        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

        <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
        
     {{-- <noscript> --}}
         <link rel="stylesheet" href="/template/css/skel-noscript.css" />
     {{-- </noscript> --}}
        
        <link rel="stylesheet" type="text/css" href="/template/css/style-desktop.css">
        <link rel="stylesheet" href="/template/css/style.css" />

        <!-- Bootstrap core CSS -->
       
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
              integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

              <!-- Latest compiled and minified CSS -->


        
        
        {{-- <link rel="stylesheet" href="/template/css/ie/v8.css" /> --}}
      
      {{-- <link rel="stylesheet" href="/template/css/ie/v9.css" /> --}}
    </head>

    @include('nav')
    <body class="homepage">
        <div id="wrapper">
            
            <!-- Header -->
            <div id="header">
                <div class="container"> 
                    
                    

                    <!-- Logo -->
                    <div id="logo">
                        <img src="/images/za.png" width="150px" height="150px">
                    </div>
                    
                    <!-- Nav -->
                   {{--  <nav id="nav">
                        <ul>
                            <li class="active"><a href="index.html">Homepage</a></li>
                            <li><a href="{{ route('auth.login') }}">User Login</a></li>
                            <li><a href="{{ route('register') }}"">Registration</a></li>
                            <li><a href="{{ route('search.index') }}">Search Job</a></li>
                            <li><a href="onecolumn.html">Employer</a></li>
                        </ul>
                    </nav> --}}
                </div>
            </div>
            <!-- /Header -->
            
            <div id="page">
                <div class="container">
                    <div class="row">
                        <div class="3u">
                            
                            <section id="sidebar1">
                                <header>
                                    <h2>Companies</h2>
                                </header>

                                
                                @foreach( $companies as $com )
                                <div style="text-align:center" class="form-control">
                                <a href=""><img src="/logo/{{ $com->logo }}" width="90px;" height="90px"></a>
                                </div>
                                    
                                
                                @endforeach;
                                
                            
                            </section>
                        </div>
                        <div class="6u skel-cell-important">
                            <section id="content" >
                                <header style="text-align: center">
                                    <h2>Jobs</h2>
                                </header>
                                

                                
                               
                                <div class="row">
                                @foreach( $jobs as $job )
                                 
                                 
                                
                                <div class="col-md-6" style="width: 800px;">  
                                
                                    
                                
                                <h3><a  href="{{ route('search.show', $job->id) }}"><strong style="color: #8e000E; font-size: 20px;">{{ $job->jobtitle }}</strong></a></h3>
                               
                                <span style="color: black; font-size: 20px;"> {{ $job->company['companyname'] }} </span>
                                
                                <hr style=" border-bottom: 3px dashed #ccc;">
                                </div>
                                
                                


                                
                                
                                
                                
                                @endforeach
                                
                                </div>
                                
                                
                            </section>
                        </div>
                        <div class="3u">
                            <section id="sidebard2">
                                <header>
                                    <h2>Sidebar 2</h2>
                                </header>
                                <ul class="style1">
                                    <li class="first"><span class="fa fa-check"></span><a href="#">Maecenas luctus lectus at sapien</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Etiam rhoncus volutpat erat</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Donec dictum metus in sapien</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Integer gravida nibh quis urna</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Etiam posuere augue sit amet nisl</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Mauris vulputate dolor nibh</a></li>
                                    <li><span class="fa fa-check"></span><a href="#">Nulla luctus eleifend purus</a></li>
                                </ul>
                                <a href="#" class="button">Full Article</a>
                            </section>
                        </div>
                    </div>

                </div>  
            </div>

            <!-- Footer -->
            <div id="footer">
                <div class="container">
                    <div class="row">
                        <div class="3u">
                            <section id="box1">
                                <header>
                                    <h2>Nulla facilisi</h2>
                                </header>
                                <ul class="style3">
                                    <li class="first">
                                        <p class="date"><a href="#">10.03.2012</a></p>
                                        <p><a href="#">Vestibulum sem magna, elementum ut, vestibulum facilisis. Nulla facilisi. Cum sociis natoque penatibus.</a></p>
                                    </li>
                                    <li>
                                        <p class="date"><a href="#">10.03.2012</a></p>
                                        <p><a href="#">Pellentesque erat erat, tincidunt in, eleifend, malesuada bibendum. Suspendisse sit amet  in eros bibendum condimentum. </a> </p>
                                    </li>
                                </ul>
                            </section>
                        </div>
                        <div class="6u">
                            <section id="box2">
                                <header>
                                    <h2>Donec dictum metus</h2>
                                </header>
                                <div> <a href="#" class="image full"><img src="images/pics02.jpg" alt=""></a> </div>
                                <p>Nulla enim eros, porttitor eu, tempus id, varius non, nibh. Duis enim nulla, luctus eu, dapibus lacinia, venenatis id, quam. Vestibulum imperdiet, magna nec eleifend rutrum, nunc lectus vestibulum velit, euismod lacinia quam nisl id lorem. Quisque erat. Vestibulum pellentesque, justo mollis pretium suscipit, justo nulla blandit libero, in blandit augue justo quis nisl.</p>
                            </section>
                        </div>
                        <div class="3u">
                            <section id="box3">
                                <header>
                                    <h2>Gravida ipsum</h2>
                                </header>
                                <ul class="style1">
                                    <li class="first"><a href="#">Pellentesque quis elit non lectus eleifend purus condimentum.</a></li>
                                    <li><a href="#">Lorem ipsum dolort, consectetuer adipiscing dictum metus sapien.</a></li>
                                    <li><a href="#">Phasellus nec dictum metus in sapien pellentesque congue.</a></li>
                                    <li><a href="#">Cras vitae metus aliquam risus dictum metus in sapien pharetra.</a></li>
                                    <li><a href="#">Duis non dictum metus in sapien ante in metus commodo euismod lobortis.</a></li>
                                </ul>
                            </section>
                        </div>
                    </div>
                </div>
            </div>

            
            
            
        </div>
    </body>
    <hr style="margin-top: 70px;">
    @include('footer') 
</html>

resources/views/errors.blade.php
@if(count($errors))
  <div class="form-group">
		<div class="alert alert-danger">
			<ul>
				@foreach($errors->all() as $error)
				<li>{{$error}}</li>
				@endforeach
			</ul>
		</div>
	</div>
</form>
@endif

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="footer, address, phone, icons" />
    <link rel="icon" href="../../../../favicon.ico">

    <title>Za</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Exo">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    
    <link rel="stylesheet" href="/footer/footer.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
    <link href="/css/layout.css" rel="stylesheet">
    <script type="text/javascript" src="/js/app.js" ></script> 

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    

</head>

<header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <img src="/images/za.png" width="50px" height="50px">&nbsp;
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      @if(auth('user')->user())
      <li class="nav-item active">
        <a style="color: #8e000E;" class="btn btn-light" href="{{ route('user') }}">Dashboard</a>
      </li>
       @else
      <li class="nav-item">
        <a style="color: #8e000E;" class="btn btn-light" href="{{ route('home.index') }}">Home</a>
      </li>
      <li class="nav-item">
        <a style="color: #8e000E;" class="btn btn-light" href="{{ route('auth.login') }}">Login</a>
      </li>
      <li class="nav-item">
        <a style="color: #8e000E;" class="btn btn-light" href="{{ route('register') }}">Register</a>
      </li>
      @endif
      <li class="nav-item">
        <a style="color: #8e000E;" class="btn btn-light" href="{{ route('search.index') }}">Search Job</a>
      </li>
    </ul>
    @if(auth('user')->user())

                    <div class="dropdown">

                        <a href="#" class=""
                           data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            {{ auth('user')->user()->firstname }}
                            <span class="caret">
                                <img class="circ" src="{{ Gravatar::get(auth('user')->user()->email)  }}">
                            </span></a>

                        <ul class="dropdown-menu">
                            <li>

                                <a style="color: blue; text-align: center" class="btn btn-light btn-block" href="{{ route('user') }}">Profile</a>
                                
                              
                                
                                <a style="color: #8e000E;" class="btn btn-light btn-block" href="#" onclick="event.preventDefault();
                                document.getElementById('logout-form').submit()">Logout</a>

                                
                                <form action="{{ route('auth.logout') }}" id="logout-form" method="POST" style="display: none">
                            {{ csrf_field() }}
                        </form>
                            </li>
                        </ul>
                    </div>
                    
                @endif   
    <form class="form-inline my-2 my-lg-0" method="POST" action="/searchjob">
      @csrf
      <input class="form-control mr-sm-2" name="searchjob" type="search" placeholder="Search" aria-label="Search">
      <button style="color: #8e000E;" class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

</header>



@yield('content')


@include('footer')

</html>

resources/views/nav.blade.php
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <img src="/images/za.png" width="50px" height="50px">&nbsp;
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a style="color: #8e000E;" class="btn btn-light" href="{{ route('home.index') }}">Home</a>
      </li>
      <li class="nav-item">
        <a style="color: #8e000E;" class="btn btn-light" href="{{ route('auth.login') }}">Login</a>
      </li>
      <li class="nav-item">
        <a style="color: #8e000E;" class="btn btn-light" href="{{ route('register') }}">Register</a>
      </li>
      <li class="nav-item">
        <a style="color: #8e000E;" class="btn btn-light" href="{{ route('search.index') }}">Search Job</a>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0" method="POST" action="/searchjob">
      @csrf
      <input class="form-control mr-sm-2" name="searchjob" type="search" placeholder="Search" aria-label="Search">
      <button style="color: #8e000E;" class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>