routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// admin login and register
Route::namespace('Auth\Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    
    Route::post('admin/login', 'LoginController@login')->name('admin.login.submit');
    
    Route::post('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::get('/admin/register', 'AregisterController@create')->name('admin.register');
Route::post('/save', 'AregisterController@store');
Route::get('/admin', 'ALoginController@index')->name('admin');
Route::get('/view', 'ALoginController@create')->name('view');
Route::resource('job','AJobController');
Route::resource('company','CompanyController');
Route::get('/detail/{id}','JobcvController@show')->name('detail');



// user login and signup
Route::namespace('Auth\User')->group(function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('auth.login');  
    Route::post('/login', 'LoginController@login')->name('login.submit');
    Route::post('/logout', 'LoginController@logout')->name('auth.logout');
});

Route::get('/register', 'RegisterController@create')->name('register');
Route::post('/post', 'RegisterController@store');


Route::resource('/', 'UserController');
Route::get('/save/{filename}', 'DownloadController@download')->name('save.cv');




// User update
Route::get('user','UpdateController@index')->name('user');
Route::get('user/profile','UserController@index')->name('profile');
Route::patch('user/profile/{id}','UserController@update');

Route::get('user/update','UpdateController@create')->name('edit');
Route::patch('/user/update/{id}','UpdateController@update')->name('update');

//Job
Route::resource('search','JobController');
Route::get('jobcv/{id}','JobcvController@store')->name('jobcv.store');
Route::get('/jobapply','JobcvController@index')->name('jobcv.index');
//Home

Route::resource('home','HomeController');

// SearchBox
Route::post('/searchjob','SearchController@Searchbox');

Route::get('/searchbycate','SearchController@searchbycate');

resources/views/admin/adminmaster.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin Dashboard</title>

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Exo">
    <!-- Bootstrap Core CSS -->
    <link href="/admindashboard/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/admindashboard/css/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="/admindashboard/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/admindashboard/css/startmin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/admindashboard/css/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/admindashboard/css/font-awesome.min.css" rel="stylesheet" type="text/css">

     

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond./admindashboard/js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <img src="/images/za.png" width="45px" height="45px">&nbsp;
</a>
        </div>

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <!-- Top Navigation: Left Menu -->


        <!-- Top Navigation: Right Menu -->
        
        <ul class="nav navbar-right navbar-top-links">
            
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color: lightgreen;">
                    <i class="fa fa-user fa-fw"></i> Admin <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    
                    
                    

                    <li class="nav-item active">
                         <a class="nav-link" href="#" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit()"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        
                        <form action="{{ route('admin.logout') }}" id="logout-form" method="POST" style="display: none">
                            {{ csrf_field() }}
                        </form>
                    </li>

                </ul>
            </li>
        </ul>

        <!-- Sidebar -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">

                <ul class="nav" id="side-menu">
                    
                    
                   
                    <li>
                        <a href="{{ route('admin') }}"><i class="fa fa-dashboard fa-fw"></i> | Home</a>
                    </li>
                    
                    <li>
                        <a href="{{ route('view') }}"><i class="fa fa-list fa-fw"></i> | CV-Lists</a>
                    </li>
                    
                    <li>
                        <a href="{{ route('job.index') }}"><i class="fa fa-suitcase fa-fw"></i> | Job</a>
                    </li>

                    <li>
                        <a href="{{ route('company.index') }}"><i class="fa fa-building fa-fw"></i> | Company</a>
                    </li>

                    <li>
                        <a href="{{ route('jobcv.index') }}"><i class="fa fa-black-tie fa-fw"></i> | User Applyed</a>
                    </li>
                    
                </ul>

            </div>
        </div>
    </nav>

    <!-- Page Content -->
</div>
@yield('content')

<!-- jQuery -->
        <script src="/admindashboard/js/jquery.min.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="/admindashboard/js/bootstrap.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="/admindashboard/js/metisMenu.min.js"></script>

        <!-- Custom Theme JavaScript -->
        <script src="/admindashboard/js/startmin.js"></script>

</body>
</html>

resources/views/admin/ahome.blade.php
@extends('admin.adminmaster')

@section('content')

<div id="page-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Dashboard</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-tasks fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge"><span>{{$jobcvcount}}</span></div>
                                        <div>User Applyed</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{{ route('jobcv.index') }}">
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-green">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-edit fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                    <div class="huge"><span>{{ $cvcount }}</span></div>
                                        <div>CV-Lists</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{{ route('view') }}">
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-yellow">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-suitcase fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">{{ $jobcount }}</div>
                                        <div>Jobs!</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{{ route('job.index') }}">
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-red">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-building fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">{{ $comcount }}</div>
                                        <div>Employers!</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{{ route('company.index') }}">
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
               




            </div>
            <!-- /#page-wrapper -->

        

@endsection

resources/views/admin/ajob.blade.php
@extends('admin.adminmaster')

@section('content')

<div id="page-wrapper">
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header">Insert A New JOB</h1>
        </div>
                    
    </div>
  <div class="row">

<form action=" {{ route('job.store') }} " method="post" class="container" style="width: 600px; background-color: #ECEFEB" enctype="multipart/form-data">
    {{ csrf_field() }}
<br>
    <div class="wrap-input form-group">
        <label for="jobtitle">JobTitle:</label>
                    
        <input type="text" name="jobtitle" maxlength="50" id="jobtitle" class="form-control" />
               
    </div>
    
    <div class="wrap-input form-group">
        <label for="companyname">CompanyName:</label>

         <select name="companyname" id="companyname" class="sign-up-select form-control">
                
                <option value="0"></option>
                @foreach($company as $comp)

                <option value="{{ $comp->id }}">{{ $comp->companyname }}</option>

                @endforeach
        </select>
    </div>
                
    
    <div class="wrap-input form-group">
        <label for="salary">Salary:</label>
                               
        <input name="salary" type="text" id="salary" class="form-control" />
    </div>


    <div class="wrap-input form-group">
        <label for="location">Location:</label>
                               
        <input name="location" type="text" id="location" class="form-control" />
    </div>
                
    
    <div class="wrap-input form-group">
        <label for="jobtime_id">Job Type/Time:</label>
        <select name="jobtime_id" id="jobtime_id" class="sign-up-select form-control">
                
                <option value="0"></option>
                    @foreach($jobtimes as $jobtime)
                    <option value="{{ $jobtime->id }}">{{ $jobtime->jobtime }}</option>
                    @endforeach

        </select>
    </div>

    <div class="wrap-input form-group">
        <label for="jobtype">Job Function</label>
        <select name="jobtype" id="jobtype" class="sign-up-select form-control" >

                    <option value="0"></option>
                    @foreach($jobtypes as $jobtype)
                    <option value="{{ $jobtype->id }}">{{ $jobtype->jobtypes }}</option>
                    @endforeach

        </select>
        
    </div>
                

    <div class="wrap-input form-group">
        <label for="description">Job Description:</label>

        <textarea name="description" id="description" class="form-control"></textarea>
    </div>

    <div class="wrap-input form-group">
        <label for="requirement">Job Requirement:</label>

        <textarea name="requirement" id="requirement" class="form-control"></textarea>
    </div>

    <div class="wrap-input form-group">
        <label for="aboutcompany">About Company:</label>

        <textarea name="aboutcompany" id="aboutcompany" class="form-control"></textarea>
    </div>

                
    <div class="wrap-input">
                    
            <input type="submit" value="Insert" class="btn btn-lg btn-success btn-block" style="width: 100%; height: 50px; cursor: pointer" />
    

            @include('errors')
                    
    </div>
<br>
</form>


      
  </div>  
</div>

@endsection

resources/views/admin/ajobdetail.blade.php
@extends('admin.adminmaster')


@section('content')


<div id="page-wrapper">
       <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Job List</h1>
            <a href="{{ route('job.create') }}" class="btn btn-lg btn-success " style="height: 50px;"/>Insert A New Job</a>
        </div>
           
               
    </div>     
                
    @foreach( $jobs as $job )
                        
        <div class="row">
               
            <div class="col">   
                    <img src="/logo/{{ $job->company['logo'] }}" width="140px" height="140px" style="float: right;">
                     
            </div>
            &nbsp;&nbsp;
            
            <div class="col-md-10">
                

                <div class="">
                    <h3 style="color: blue">{{ $job->jobtitle }} *</h3>
                </div>

                <div class="">
                    <h4 style="color: green">[ {{ $job->company['companyname'] }} ]</h4>
                </div>

                <div>
                    
                    <label><strong>Salary: </strong>[ {{ $job->salary }} ]</label>
                </div>
                <div>
                    
                    <label><strong>Location:  </strong>[ {{ $job->location }} ]</label>
                
                </div>
                
            
                <div>
                    <label><strong>Job Function:  </strong>[ {{ $job->jobtypes['jobtypes'] }} ]</label>
                
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    

                    <label><strong>Posted:  </strong>[ {{ $job->created_at }} ]</span></label>
                
                </div>
                                
                <button class="btn btn-primary">Edit</button>
                <button class="btn btn-primary">Delete</button>     
            </div>
                     
            

          </div>  
        <hr style="border-width: 30px;">
        @endforeach                   
            
                
    </div>

@endsection

resources/views/admin/amaster.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>FindOne</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Exo">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    

    <!-- Custom styles for this template -->
    <link href="css/layout.css" rel="stylesheet">
</head>


<header>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" style=" height: 65px;">
        <img src="/images/za.png" width="50px" height="50px">&nbsp;

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto" >

                &nbsp; &nbsp;

                @if(auth('admin')->user())
                    <li class="nav-item active" style="padding-left: 860px;">
                        <a class="nav-link btn btn-success" href="#" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit()">Logout </a>
                        <form action="{{ route('admin.logout') }}" id="logout-form" method="POST" style="display: none">
                            {{ csrf_field() }}
                        </form>
                    </li>
                @endif
            </ul>

            

        </div>
    </nav>

</header>

<body style="background-color: #F5F5F5;">
@yield('content')
</body>



</html>

resources/views/admin/aregister.blade.php
@extends('admin.amaster')

@section('content')


<div class="container" style="padding-bottom: 100px; margin-top: 150px;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

                <div class="card-body">
                    <form method="POST" action="/save">
                        @csrf

                        

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>





@endsection

resources/views/admin/company.blade.php
@extends('admin.adminmaster')

@section('content')

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Insert Company Info</h1>
        </div>
                    
    </div>
<form action=" {{ route('company.store') }} " method="post" class="container" style="width: 600px; background-color: #ECEFEB" enctype="multipart/form-data">
    {{ csrf_field() }}
<br>
    <div class="wrap-input form-group">
        <label for="companyname">Company Name:</label>
                    
        <input type="text" name="companyname" maxlength="50" id="companyname" class="form-control" />
               
    </div>
    
    <div class="wrap-input form-group">
        <label for="email">Email Address:</label>

        <input name="email" type="text" class="form-control" id="email" />
    </div>
                
    
    <div class="wrap-input form-group">
        <label for="phone">Phone:</label>
                               
        <input name="phone" type="text" id="phone" class="form-control" />
    </div>


    <div class="wrap-input form-group">
        <label for="aboutcompany">About Company:</label>

        <textarea name="aboutcompany" id="aboutcompany" class="form-control"></textarea>
    </div>

    <div class="wrap-input form-group">
        <div>
            <label>Company Logo</label>

        </div>

        <div style="display: inline-block; width: 100%;">
            <input type="file" name="logo" id="logo" class="form-control" />

        </div>
    </div>

                
    <div class="wrap-input">
                    
            <input type="submit" value="Finish" class="btn btn-lg btn-success btn-block" style="width: 100%; height: 50px; cursor: pointer" />
    

            @include('errors')
                    
    </div>
<br>
</form>


</div>

@endsection

resources/views/admin/companydetail.blade.php
@extends('admin.adminmaster')

@section('content')

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Company List</h1>
            
        </div>
    </div>
    
    <div class="row">
      
      
      <img src="/logo/{{ $company->logo }} " style="width: 150px; height: 150px;" >
      <h2 style="color: green">{{ $company->companyname }}</h2>

      <br>
      <div>
      <i class="fa fa-envelope" style="font-size: 20px"> Email Address : {{ $company->email }} </i>
      </div>

      <br>
      <div>
      <i class="fa fa-tty" style="font-size: 20px"> Phone : {{ $company->phone }} </i>
      </div>

      <br>
      <div>
      <i class="fa fa-align-center" style="font-size: 20px"> About Company : <br><br>{{ $company->aboutcompany }} </i>
      </div>
      
    </div>
    
       

    

            
  






</div>



@endsection

resources/views/admin/companylist.blade.php
@extends('admin.adminmaster')

@section('content')

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Company List</h1>
            <a href="{{ route('company.create') }}" class="btn btn-lg btn-success " style="height: 50px;"/>Insert Company</a>
        </div>
           
               
    </div>
    
    <br>
    
        <div class="row">
            <div class="col-md-12">
            
        @foreach($company as $comp)


       
            <div class="col-md-4">
             <div class="thumbnail">
               <img src="/logo/{{ $comp->logo }} " style="width: 150px; height: 150px;" >
                <div class="caption">
                 <h3 style="text-align: center">{{ $comp->companyname }}
                    <p>
                        <a href="{{ route('company.show', $comp->id) }}" class="btn btn-primary" role="button">View</a>
                    
                        <a href="#" class="btn btn-primary" role="button">Edit</a>
                    
                        <a href="#" class="btn btn-primary" role="button">Delete</a>


                    </p>
                </h3>
                  
                        
                    </div>
                    </div>
                </div>
        
                
        @endforeach
       {{-- </div>  --}}
       </div>
    </div>
    
  <hr> 
    

            
  






</div>

@endsection

resources/views/admin/detailjob.blade.php
@extends('admin.adminmaster')

@section('content')

<div id="page-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Detail Info</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
<div class="row">

<br>         


@foreach($jobcvs as $jobcv)
	<div>                
    <label><strong>Email: </strong> {{ $jobcv->users['email'] }} </label>
    </div>  
    
    <div>    
    <label><strong>Firstname:  </strong> {{ $jobcv->users['firstname'] }} </label>           
    </div>

    <div>    
    <label><strong>Lastname:  </strong> {{ $jobcv->users['lastname'] }} </label>           
    </div>

    <div>    
    <label><strong>Phone:  </strong> {{ $jobcv->users['phone'] }} </label>           
    </div>

    <div>    
    <label><strong>Title:  </strong> {{ $jobcv->users['title'] }} </label>           
    </div>

    <div>    
    <label><strong>JobType:  </strong> {{ $jobcv->jobs['jobtypes']->jobtypes }} </label>           
    </div>

    <div>    
    <label><strong>Job Type/Time:  </strong> {{ $jobcv->jobs['jobtime']->jobtime }} </label>           
    </div>

    <div>    
    <label><strong>Location:  </strong> {{ $jobcv->users['title'] }} </label>           
    </div>
		
		
		<a href="{!! route('save.cv', $jobcv->users['cv']) !!}" target="_blank"> Click to download CV </a>
	
@endforeach

</table>
               
            </div>
            <hr>
      	@foreach( $jobcvs as $jobcv )
                        
        <div class="row">
               
            <div class="col">   
                    <img src="/logo/{{ $jobcv->companies['logo'] }}" width="140px" height="140px" style="float: right;">
                     
            </div>
            &nbsp;&nbsp;
            
            <div class="col-md-10">
                

                <div class="">
                    <h3 style="color: blue">{{ $jobcv->jobs['jobtitle'] }} *</h3>
                </div>

                <div class="">
                    <h4 style="color: green">{{ $jobcv->companies['companyname'] }} </h4>
                </div>

                <div>
                    
                    <label><strong>Salary: </strong> {{ $jobcv->jobs['salary'] }} </label>
                </div>
                <div>
                    
                    <label><strong>Location:  </strong> {{ $jobcv->jobs['location'] }} </label>
                
                </div>

                <div>
                    
                    <label><strong>Job Time/Type:  </strong> {{ $jobcv->jobs['jobtime']->jobtime }} </label>
                
                </div>
                
            			
                <div>
                    <label><strong>Job Function:  </strong> {{ $jobcv->jobs['jobtypes']->jobtypes }} </label>
               
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    

                    <label><strong>Posted:  </strong> {{ $jobcv->jobs['created_at'] }} </span></label>
                <hr>
                </div>
                                
                   
            </div>
                     
            

          </div>  
        
        @endforeach 

        </div>

@endsection